//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yazlab1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan
    {
        public int Loan_Id { get; set; }
        public Nullable<int> Book_Id { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<System.DateTime> Deliver_Date { get; set; }
    }
}
